### ISSUE TITLE
diff default to today

### ISSUE THREAD

**Issue by AdrienLemaire** [jarun/pdd#17]
Hi @jarun and thank you for all your delightful tools.

I often find myself looking for the number of days remaining from today to X.

Right now, I can get it as follow:
```console
$ pdd -d 2020 Jul 5 $(date +"%Y %b %d")
0y 2m 26d
87d
```

But it would be simpler to just type:
```console
$ pdd -d 2020 Jul 5
usage: pdd [-h] [-d yyyy mmm dd [yyyy mmm dd | y m d]] [-t hh:mm:ss [hh:mm:ss | h:m:s]] [--add] [--sub] [--day yyyy mmm dd] [-c hh:mm:ss] [-r command] [-s [resolution]] [-q] [keywords [keywords ...]]
pdd: error: argument -d: expected 6 arguments
```

Can you make it so that if only 3 arguments are given to `pdd -d`, the remaining 3 are auto-evaluated to today?

**Comment by jarun** [comment]
It's the simplest! Please see the first example:

```
$ pdd 2020 Jul 5       
0y 2m 26d
87d
```

**Comment by AdrienLemaire** [comment]
Oh boy. Sorry about that, and thanks for the reply!
