### ISSUE TITLE
Can it "add" more than two timestamps?

### ISSUE THREAD

**Issue by biy37273** [jarun/pdd#19]
First thanks for this very helpful tool, 
i frequently need to determine the differences between two timestamps
and this tool really helps me!

about the `--add` option, can it work with more than two timestamps ?
e.g 
```
pdd -t 00:01:00 00:02:00 00:03:00 --add
```
results:
```
00:03:00
180s
08:11:54
29514s
```
expected results:
```
00:06:00
360s
```

or if there another workflow/approach i will be grateful.

note: my plan is to add dozens of timestamps, not just three. thanks in advance

**Comment by jarun** [comment]
No, 2 timestamps only. However, please go through the current code. Probably you will be able to extend it easily.
