### ISSUE TITLE
How to use the zsh_completion.py script ?

### ISSUE THREAD

**Issue by Antiz96** [jarun/pdd#23]
Hi,

I'm trying to update `pdd` (pdd-git) to V1.6 on the AUR but I'm struggling with the zsh completion.

For `ddgr` (which I also maintain on the AUR), the `_ddgr` file for zsh completion is already provided in the archive, but with `pdd` I have to generate the `_pdd` file myself during the packaging process by executing the `zsh_completion.py`, is that right ?

If that's so, I cannot seems to make it work... Here the result I get:
`python zsh_completion.py`
```
Traceback (most recent call last):
  File "/tmp/pdd/src/pdd/auto-completion/zsh/zsh_completion.py", line 121, in <module>
    parser = __import__(PACKAGE).get_parser()
ModuleNotFoundError: No module named 'pdd'
```
Unfortunately, I'm not good enough with python to find my way out.

Can you help me generating the zsh completion file ?
Thanks in advance !

BTW, thanks for your awesome works :)

**Comment by hltdev8642** [comment]
Just an alternative option that worked for me, copy the bash completion file to wherever you keep your zsh completions.

I renamed it to `_pdd` (from `pdd.bash`). 

Then restart zsh and for me this yields a working completin

**Comment by jarun** [comment]
Yes, bash and zsh are similar.

@Freed-Wu please have a look why the script is failing.

**Comment by Freed-Wu** [comment]
Please `cp pdd pdd.py` firstly. Because module which python can import must be suffexed with `.py`.

**Comment by Freed-Wu** [comment]
Maybe we should add `install_shell_completions` to `Makefile` to reduce packagers' hardness?

**Comment by Freed-Wu** [comment]
> Not everyone uses every shell.

I know. I means `make install` to install binary file and `make install-all` install binary file and completions.

**Comment by jarun** [comment]
We can have that.

**Comment by Freed-Wu** [comment]
> We can have that.

OK, #25 should be you need.

**Comment by Antiz96** [comment]
> No. Not everyone uses every shell.

Even though not everyone's using every shell, is there anything preventing to install the completions anyway?
I mean, I'm not using zsh (I don't even have it installed), but I still have a lot of zsh completion from packages in `/usr/share/zsh/site-functions`.
If you allow me, I would suggest having them installed in any case, this is what every other packages seems to do.
