### ISSUE TITLE
[advice] Change shtab

### ISSUE THREAD

**Issue by Freed-Wu** [jarun/pdd#26]
I propose use some library like <https://docs.iterative.ai/shtab> to generate shell completion. Just

```sh
pdd --print-completion XXX
```

Maybe easier. One hard problem is `shtab` doesn't support generate shell completion for `nargs > 1`.
I advise change `pdd -d yyyy mmm dd` to `pdd -d yyyy-mmm-dd` to avoid this problem.

Advantage:

- shtab can be an extras_require, which will not import any necessary requirement.
- Share code about completion with many python projects. Like
  - <https://github.com/andreafrancia/trash-cli/blob/master/setup.cfg#L31-L33>
  - <https://github.com/inducer/pudb/blob/main/setup.py#L28>
  - <https://github.com/piccolomo/plotext/blob/master/setup.py#L25>
  - <https://github.com/wookayin/gpustat/blob/master/setup.py#L114>

Disadvantage:

- Break the compatibility

**Comment by jarun** [comment]
I think we are good with what we have now.
