### ISSUE TITLE
feature: command line option -v, --version

### ISSUE THREAD

**Issue by bwagner** [jarun/pdd#28]
feature request: version number, i.e. command line option -v, --version
I plan to provide a PR soon.

**Comment by jarun** [comment]
`pdd -h` shows the version.

**Comment by bwagner** [comment]
Agreed. The version as a dedicated command line option is kind of standard, though. I provided a [PR](https://github.com/jarun/pdd/pull/29). It's your call of course.

**Comment by jarun** [comment]
Closed at #29.
