### ISSUE TITLE
Availability on PyPI

### ISSUE THREAD

**Issue by dmarcoux** [jarun/pdd#5]
Hey,

Would it be possible to have `pdd` on [PyPi](https://pypi.org/)?

**Comment by dmarcoux** [comment]
I have never done it, but I will give it a go. I will send a PR soon.

**Comment by jarun** [comment]
Sure! Thanks!

**Comment by jarun** [comment]
Will wait for the PR. Closing this issue.

**Comment by dmarcoux** [comment]
Now available at https://pypi.org/project/pdd/

**Comment by jarun** [comment]
Awesome! 👍 Thank you!
