### ISSUE TITLE
Customizable time/date diff output

### ISSUE THREAD

**Issue by mrshu** [jarun/pdd#9]
Hi @jarun, thanks a ton for a very useful tool!

As I understand it, `pdd` (the command line tool) currently only outputs the time difference In the following format:

```
%02d:%02d:%02d
%ds
```

I was wondering if it would be possible to add an option to change that on run time.

Thanks a ton!

**Comment by jarun** [comment]
Hi,

Somehow I missed this big time.
Can you please raise a PR to do this? Probably an environment variable which the utility would read and follow.

**Comment by jarun** [comment]
There are issues with using `strftime`. Here's a crude example:

```
~/G/pdd$ gd
diff --git a/pdd b/pdd
index f1d48e7..f679222 100755
--- a/pdd
+++ b/pdd
@@ -19,8 +19,8 @@
 
 import argparse
 import calendar as cal
-from datetime import date
-from datetime import datetime
+import datetime
+#from datetime import datetime
 from dateutil.relativedelta import relativedelta
 import os
 import sys
@@ -129,14 +129,8 @@ def showtimediff(t0, t1):
 
     m, s = divmod(abs(t0 - t1), 60)
     h, m = divmod(m, 60)
-    d, h = divmod(h, 24)
-
-    if d > 0:
-        print('day %d, %02d:%02d:%02d' % (d, h, m, s))
-    else:
-        print('%02d:%02d:%02d' % (h, m, s))
-
-    print('%ds' % abs(t0 - t1))
+    t = datetime.time(h, m, s)
+    print(t.strftime('%H %M %S'))
 
 
 def showtimesum(t0, t1):
~/G/pdd$ ./pdd -t 28:00:00 1:01:59
error: hour must be in 0..23
```

Currently this works like a charm and shows the number of days.
